### ISSUE TITLE
Error: got 401 response

### ISSUE THREAD

**Issue by hxuanhung** [danshumaker/bitbucket-cmd#4]
I tried to follow the instruction but got Error: got 401 response.

**Comment by danshumaker** [comment]
Hi Hxuan,
I'll bet it's an issue with the repo name you entered in during configuration.

Can you paste your config.json file in the this issue comment and then null out your token value ?

It should look something like this:

`{
  "auth": {
    "url": "https://api.bitbucket.org/2.0/repositories/phase2tech/mti_cms/",
    "user": "dan_shumaker",
    "token": "bla_bla_bla_dont_paste_your_real_token_obviously"
  },
  "options": {
    "default_reviewers": [ { "username" : "ezeedub"  }  ]
  }
}
`

**Comment by hxuanhung** [comment]
I have double checked it and you are right 👍 . However I think we can improve the error message to be more precise.
