### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by Karolusrex** [danshumaker/bitbucket-cmd#6]
`npm install -g bitbucket-cmd`

` Error extracting /Users/<User>/.npm/bitbucket-cmd/0.3.0/package.tgz archive: ENOENT: no such file or directory, open '/Users/<User>/.npm/bitbucket-cmd/0.3.0/package.tgz'`

**Comment by palashkulsh** [comment]
@Karolusrex can you please mention node & npm versions & operating system being used.

**Comment by Karolusrex** [comment]
Thanks for your response. It worked now when I tried again, not sure what the delta is. I'll close this issue. Thanks for making open source!!!!
