### ISSUE TITLE
Doesn't work with hosted version of Bitbucket

### ISSUE THREAD

**Issue by gbajaj** [danshumaker/bitbucket-cmd#8]
is it possible to add support for the hosted bitbucket repos
**http://example.com/rest/api/1.0/projects/{**projectKey}/repos/{repositorySlug}/**pull-requests**

**Comment by palashkulsh** [comment]
@gbajaj I can try to work on its support in my fork if you want.

**Comment by gbajaj** [comment]
@palashkulsh I tried to make changes in pr.js and and replace "pullrequests" with "pull-requests" as a first change that I think would fix the problem. The challenge i faced was that i couldn't get to install my changed files. How do you install the modified version? I appreciate your help

**Comment by palashkulsh** [comment]
@gbajaj you can take the following steps
1. take the fork of the repo
2. pull that fork
3. make changes in your forked repo
4. push those changes in your forked repo
5. install the npm module as
npm install -g gbajaj/bitbucket-cmd#branch

i think this should set you up
